version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/app:cached
    command:
      tail -f /dev/null
    ports:
      - "8080:8080"
